// src/lib/components/profiles/ProfileMenu.svelte
<script lang="ts">
  import { Download, Copy, RotateCcw, Trash2 } from 'lucide-svelte';
  import { slide } from 'svelte/transition';

  interface Props {
    profileId: number;
    position: { top: number; right: number };
    isActive: boolean;
    canDelete: boolean;
    onExport: () => void;
    onDuplicate: () => void;
    onRestore: () => void;
    onDelete: () => void;
  }

  let {
    profileId,
    position,
    isActive,
    canDelete,
    onExport,
    onDuplicate,
    onRestore,
    onDelete,
  }: Props = $props();

  // Long press delete state
  let isHolding = $state(false);
  let holdProgress = $state(0);
  let holdTimer: ReturnType<typeof setInterval> | null = null;
  const HOLD_DURATION = 1500; // 1.5 seconds
  const UPDATE_INTERVAL = 16; // ~60fps

  function startHold(e: MouseEvent | TouchEvent) {
    e.preventDefault();
    isHolding = true;
    holdProgress = 0;

    holdTimer = setInterval(() => {
      holdProgress += (UPDATE_INTERVAL / HOLD_DURATION) * 100;

      if (holdProgress >= 100) {
        cancelHold();
        onDelete();
      }
    }, UPDATE_INTERVAL);
  }

  function cancelHold() {
    isHolding = false;
    holdProgress = 0;
    if (holdTimer) {
      clearInterval(holdTimer);
      holdTimer = null;
    }
  }

  // Cleanup on unmount
  $effect(() => {
    return () => {
      if (holdTimer) clearInterval(holdTimer);
    };
  });
</script>

<div
  class="fixed border rounded-lg shadow-2xl z-[9999] w-48 overflow-hidden backdrop-blur-2xl glassmorphism-card border-primary-500/30"
  style="top: {position.top}px; right: {position.right}px;"
  transition:slide={{ duration: 150, axis: 'y' }}
  onclick={e => e.stopPropagation()}
  onkeydown={e => e.stopPropagation()}
  role="menu"
  tabindex={-1}
>
  <button
    class="w-full px-4 py-2.5 text-left text-sm hover:bg-primary-800/50 flex items-center gap-3 text-gray-200 dark:text-gray-200 transition-colors"
    onclick={onExport}
  >
    <Download class="w-4 h-4" />
    Export
  </button>

  <button
    class="w-full px-4 py-2.5 text-left text-sm hover:bg-primary-800/50 flex items-center gap-3 text-gray-200 dark:text-gray-200 transition-colors"
    onclick={onDuplicate}
  >
    <Copy class="w-4 h-4" />
    Duplicate
  </button>

  <button
    class="w-full px-4 py-2.5 text-left text-sm hover:bg-primary-800/50 flex items-center gap-3 text-gray-200 dark:text-gray-200 transition-colors"
    onclick={onRestore}
  >
    <RotateCcw class="w-4 h-4" />
    Restore Default
  </button>

  {#if canDelete && !isActive}
    <div class="border-t border-primary-700/50"></div>
    <button
      class="w-full px-4 py-2.5 text-left text-sm flex items-center gap-3 text-red-400 transition-all relative overflow-hidden {isHolding
        ? 'bg-red-900/30'
        : 'hover:bg-red-900/20'}"
      onmousedown={startHold}
      ontouchstart={startHold}
      onmouseup={cancelHold}
      onmouseleave={cancelHold}
      ontouchend={cancelHold}
    >
      <!-- Progress bar background -->
      <div
        class="absolute inset-0 bg-red-900/40 transition-none"
        style="width: {holdProgress}%;"
      ></div>

      <!-- Content -->
      <span class="relative z-10 flex items-center gap-3 w-full">
        {#if isHolding}
          <div class="w-4 h-4 relative">
            <!-- Circular progress spinner -->
            <svg class="w-4 h-4 rotate-[-90deg]" viewBox="0 0 16 16">
              <circle
                cx="8"
                cy="8"
                r="6"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                class="opacity-30"
              />
              <circle
                cx="8"
                cy="8"
                r="6"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-dasharray={holdProgress * 0.377}
                stroke-dashoffset="0"
                stroke-linecap="round"
              />
            </svg>
          </div>
          <span class="flex-1">
            {holdProgress >= 100 ? 'Deleted!' : `Deleting... ${Math.floor(holdProgress)}%`}
          </span>
        {:else}
          <Trash2 class="w-4 h-4" />
          <span>Hold to Delete (1.5s)</span>
        {/if}
      </span>
    </button>
  {/if}
</div>

// src/features/profiles/components/ProfileMenu.tsx
import { Copy, Download, RotateCcw, Trash2 } from 'lucide-react';
import { useEffect, useLayoutEffect, useRef, useState, type KeyboardEvent, type Ref } from 'react';

/** Holding Delete for this long deletes the profile. */
const HOLD_DURATION = 1500;
/** Progress updates while holding (~60 fps). */
const UPDATE_INTERVAL = 16;

export interface ProfileMenuPosition {
  readonly top: number;
  readonly right: number;
}

export interface ProfileMenuProps {
  /** Viewport offsets of the menu (below its menu button, right-aligned). */
  readonly position: ProfileMenuPosition;
  readonly isActive: boolean;
  readonly canDelete: boolean;
  readonly onExport: () => void;
  readonly onDuplicate: () => void;
  readonly onRestore: () => void;
  readonly onDelete: () => void;
  /** Root element, for the page's slide transition. */
  readonly ref?: Ref<HTMLDivElement>;
}

const itemClass =
  'w-full px-4 py-2.5 text-left text-sm hover:bg-primary-800/50 flex items-center gap-3 text-gray-200 dark:text-gray-200 transition-colors';

function isActivationKey(event: KeyboardEvent): boolean {
  return event.key === 'Enter' || event.key === ' ';
}

/**
 * A profile card's menu (port of `profiles/ProfileMenu.svelte`): Export, Duplicate, Restore
 * Default and, for inactive additional profiles, hold-to-delete (1.5 s).
 */
export function ProfileMenu({
  position,
  isActive,
  canDelete,
  onExport,
  onDuplicate,
  onRestore,
  onDelete,
  ref,
}: ProfileMenuProps) {
  const [isHolding, setIsHolding] = useState(false);
  const [holdProgress, setHoldProgress] = useState(0);
  const latestOnDelete = useRef(onDelete);

  useLayoutEffect(() => {
    latestOnDelete.current = onDelete;
  });

  const startHold = () => {
    setIsHolding(true);
    setHoldProgress(0);
  };

  const cancelHold = () => {
    setIsHolding(false);
    setHoldProgress(0);
  };

  // While holding, progress advances every 16 ms; at 100 % the profile is deleted.
  useEffect(() => {
    if (!isHolding) return;
    let progress = 0;
    const timer = setInterval(() => {
      progress += (UPDATE_INTERVAL / HOLD_DURATION) * 100;
      setHoldProgress(progress);
      if (progress >= 100) {
        setIsHolding(false);
        setHoldProgress(0);
        latestOnDelete.current();
      }
    }, UPDATE_INTERVAL);
    return () => {
      clearInterval(timer);
    };
  }, [isHolding]);

  return (
    <div
      ref={ref}
      className="fixed border rounded-lg shadow-2xl z-[9999] w-48 overflow-hidden backdrop-blur-2xl glassmorphism-card border-primary-500/30"
      style={{ top: `${position.top}px`, right: `${position.right}px` }}
      onClick={event => {
        event.stopPropagation();
      }}
      onKeyDown={event => {
        event.stopPropagation();
      }}
      role="menu"
      tabIndex={-1}
    >
      <button type="button" role="menuitem" className={itemClass} onClick={onExport}>
        <Download className="w-4 h-4" />
        Export
      </button>

      <button type="button" role="menuitem" className={itemClass} onClick={onDuplicate}>
        <Copy className="w-4 h-4" />
        Duplicate
      </button>

      <button type="button" role="menuitem" className={itemClass} onClick={onRestore}>
        <RotateCcw className="w-4 h-4" />
        Restore Default
      </button>

      {canDelete && !isActive && (
        <>
          <div className="border-t border-primary-700/50" />
          <button
            type="button"
            role="menuitem"
            className={`w-full px-4 py-2.5 text-left text-sm flex items-center gap-3 text-red-400 transition-all relative overflow-hidden ${
              isHolding ? 'bg-red-900/30' : 'hover:bg-red-900/20'
            }`}
            onMouseDown={event => {
              event.preventDefault();
              startHold();
            }}
            onTouchStart={startHold}
            onMouseUp={cancelHold}
            onMouseLeave={cancelHold}
            onTouchEnd={cancelHold}
            onKeyDown={event => {
              if (!isActivationKey(event) || event.repeat) return;
              event.preventDefault();
              startHold();
            }}
            onKeyUp={event => {
              if (isActivationKey(event)) cancelHold();
            }}
            onBlur={cancelHold}
          >
            {/* Progress bar background */}
            <div
              className="absolute inset-0 bg-red-900/40 transition-none"
              style={{ width: `${holdProgress}%` }}
            />

            {/* Content */}
            <span className="relative z-10 flex items-center gap-3 w-full">
              {isHolding ? (
                <>
                  <div className="w-4 h-4 relative">
                    {/* Circular progress spinner */}
                    <svg className="w-4 h-4 rotate-[-90deg]" viewBox="0 0 16 16">
                      <circle
                        cx="8"
                        cy="8"
                        r="6"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        className="opacity-30"
                      />
                      <circle
                        cx="8"
                        cy="8"
                        r="6"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                        strokeDasharray={holdProgress * 0.377}
                        strokeDashoffset="0"
                        strokeLinecap="round"
                      />
                    </svg>
                  </div>
                  <span className="flex-1">
                    {holdProgress >= 100 ? 'Deleted!' : `Deleting... ${Math.floor(holdProgress)}%`}
                  </span>
                </>
              ) : (
                <>
                  <Trash2 className="w-4 h-4" />
                  <span>Hold to Delete (1.5s)</span>
                </>
              )}
            </span>
          </button>
        </>
      )}
    </div>
  );
}
