// src/features/dynamic-keys/components/ToggleMode.tsx
/**
 * Toggle editor (port of `advancedkey/ToggleMode.svelte`): a toggle key on the first selected key
 * of the selected layer. Apply writes it with `applyDynamicKey` (D6); trigger and state are
 * UI-only (D5); the configured list and its deletes are the keyboard's toggle keys.
 */
import { useState } from 'react';
import { NoKeySelected } from '../../../components/ui';
import {
  deviceSession,
  deviceStore,
  useDeviceConfig,
  type DeviceConfig,
  type KeyLocation,
} from '../../device';
import { useSelectedKeys, useSelectedLayer } from '../../keyboard';
import { useT } from '../../../lib/i18n';
import { removeDynamicKeyAt, removeDynamicKeysOfKind } from '../commands';
import { useLoadedDraft } from '../hooks/use-loaded-draft';
import { useTimeouts } from '../hooks/use-timeouts';
import {
  configuredKeys,
  dynamicKeyOfKindAt,
  dynamicKeySignature,
  locationKey,
  type ConfiguredKey,
} from '../model/configured-keys';
import {
  TOGGLE_DRAFT,
  loadToggleDraft,
  toggleDraft,
  type ToggleDraft,
} from '../model/editor-drafts';
import { keyIndexName } from '../model/key-names';
import { uiFields, uiFieldsStore, useUiFields, type UiFieldsState } from '../store/ui-fields';
import { NO_KEYS, withKey, withKeys, withoutKey } from './shared/key-sets';
import { KeycodePicker } from './shared/KeycodePicker';
import { ToggleConfiguredKeys } from './toggle/ToggleConfiguredKeys';
import {
  ToggleHeader,
  ToggleInfoPanel,
  ToggleModeSelector,
  TogglePreview,
  ToggleSelectedKeyInfo,
  ToggleStateControl,
} from './toggle/ToggleParts';

const DELETE_ANIMATION_MS = 500;
const ADDED_ANIMATION_MS = 600;

/** What the editor loads from: the key, its toggle and its remembered trigger/state. */
function toggleSource(
  config: DeviceConfig | null,
  toggle: UiFieldsState['toggle'],
  target: KeyLocation | null
) {
  const found = dynamicKeyOfKindAt(config, target, 'toggle');
  const fields = target ? toggle[locationKey(target)] : undefined;
  return {
    toggle: found,
    fields,
    deps: [target && locationKey(target), dynamicKeySignature(found?.dynamicKey ?? null), fields],
  };
}

export interface ToggleModeProps {
  readonly onBack: () => void;
}

export function ToggleMode({ onBack }: ToggleModeProps) {
  const t = useT();
  const selectedKeys = useSelectedKeys();
  const layer = useSelectedLayer();
  const config = useDeviceConfig();
  const toggleFields = useUiFields(state => state.toggle);
  const schedule = useTimeouts();

  const currentSelectedIndex = selectedKeys[0] ?? null;
  const target: KeyLocation | null =
    currentSelectedIndex === null ? null : { layer: layer - 1, id: currentSelectedIndex };
  const source = toggleSource(config, toggleFields, target);
  const { draft, update, adopt } = useLoadedDraft<ToggleDraft>(
    source.deps,
    () => loadToggleDraft(source.toggle?.dynamicKey ?? null, source.fields),
    () => TOGGLE_DRAFT
  );
  const [toggleDeletingKeys, setToggleDeletingKeys] = useState(NO_KEYS);
  const [toggleNewlyAddedKeys, setToggleNewlyAddedKeys] = useState(NO_KEYS);

  const configuredToggleKeys = configuredKeys(config?.dynamicKeys ?? [], 'toggle');
  const currentKeyName =
    currentSelectedIndex === null ? 'No key selected' : keyIndexName(currentSelectedIndex);

  function deleteToggleKey(entry: ConfiguredKey<'toggle'>): void {
    const keyId = locationKey(entry.target);
    setToggleDeletingKeys(keys => withKey(keys, keyId));
    schedule(
      () => {
        removeDynamicKeyAt(entry.target, 'toggle');
        setToggleDeletingKeys(keys => withoutKey(keys, keyId));
      },
      DELETE_ANIMATION_MS,
      { flushOnUnmount: true }
    );
  }

  function resetAllToggleKeys(): void {
    const keysToDelete = configuredToggleKeys.map(entry => locationKey(entry.target));
    setToggleDeletingKeys(keys => withKeys(keys, keysToDelete));
    schedule(
      () => {
        removeDynamicKeysOfKind('toggle');
        setToggleDeletingKeys(NO_KEYS);
      },
      DELETE_ANIMATION_MS,
      { flushOnUnmount: true }
    );
  }

  function applyToggleConfiguration(): void {
    if (!target) return;
    const keyId = locationKey(target);
    const isNewKey = source.toggle === null;
    // null: no free slot; the editor keeps its values (the device layer logs the rejection).
    if (deviceSession.applyDynamicKey(toggleDraft(target, draft)) === null) return;
    uiFields.setToggle(target, { trigger: draft.trigger, state: draft.state });
    adopt(
      draft,
      toggleSource(deviceStore.getState().config, uiFieldsStore.getState().toggle, target).deps
    );
    if (isNewKey) {
      setToggleNewlyAddedKeys(keys => withKey(keys, keyId));
      schedule(() => {
        setToggleNewlyAddedKeys(keys => withoutKey(keys, keyId));
      }, ADDED_ANIMATION_MS);
    }
  }

  return (
    <>
      <ToggleHeader
        onBack={onBack}
        onApply={applyToggleConfiguration}
        onResetAll={resetAllToggleKeys}
        canApply={currentSelectedIndex !== null}
      />

      <div className="p-4 sm:p-6 -mx-8">
        {currentSelectedIndex !== null ? (
          <div className="max-w-7xl mx-auto">
            <ToggleSelectedKeyInfo
              currentKeyName={currentKeyName}
              currentSelectedIndex={currentSelectedIndex}
              toggleState={draft.state}
            />

            <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
              <div className="xl:col-span-2 space-y-6">
                <KeycodePicker
                  title={t('advancedkey.toggleAction')}
                  selectedAction={draft.binding}
                  onActionSelect={binding => {
                    update(current => ({ ...current, binding }));
                  }}
                  defaultExpandedSection="Basic"
                />

                <ToggleModeSelector
                  toggleMode={draft.trigger}
                  onModeSelect={trigger => {
                    update(current => ({ ...current, trigger }));
                  }}
                />

                <ToggleStateControl
                  toggleState={draft.state}
                  onStateToggle={() => {
                    update(current => ({ ...current, state: !current.state }));
                  }}
                />
              </div>

              <div className="xl:col-span-1 space-y-6">
                <TogglePreview
                  currentKeyName={currentKeyName}
                  selectedToggleAction={draft.binding}
                  toggleMode={draft.trigger}
                  toggleState={draft.state}
                />
                <ToggleInfoPanel selectedToggleAction={draft.binding} toggleMode={draft.trigger} />

                {configuredToggleKeys.length > 0 && (
                  <ToggleConfiguredKeys
                    configuredKeys={configuredToggleKeys}
                    deletingKeys={toggleDeletingKeys}
                    newlyAddedKeys={toggleNewlyAddedKeys}
                    onDeleteKey={deleteToggleKey}
                  />
                )}
              </div>
            </div>
          </div>
        ) : (
          <NoKeySelected tipKey="advancedkey.toggleTip" />
        )}
      </div>
    </>
  );
}

// src/lib/components/advancedkey/ToggleMode.svelte
<script lang="ts">
  import { language, t } from '$lib/stores/LanguageStore.svelte';
  import { selectedKeys } from '$lib/stores/SelectedKeysStore';
  import { keyboardAPI } from '$lib/api/keyboardAPI.svelte';
  import {
    globalConfigurations,
    updateGlobalConfiguration,
    resetGlobalConfiguration,
  } from '$lib/types/AdvancedKeyShared';

  import ToggleHeader from '$lib/components/advancedkey/toggle/ToggleHeader.svelte';
  import ToggleSelectedKeyInfo from '$lib/components/advancedkey/toggle/ToggleSelectedKeyInfo.svelte';
  import ToggleActionSelector from '$lib/components/advancedkey/toggle/ToggleActionSelector.svelte';
  import ToggleModeSelector from '$lib/components/advancedkey/toggle/ToggleModeSelector.svelte';
  import ToggleStateControl from '$lib/components/advancedkey/toggle/ToggleStateControl.svelte';
  import TogglePreview from '$lib/components/advancedkey/toggle/TogglePreview.svelte';
  import ToggleInfoPanel from '$lib/components/advancedkey/toggle/ToggleInfoPanel.svelte';
  import ToggleConfiguredKeys from '$lib/components/advancedkey/toggle/ToggleConfiguredKeys.svelte';
  import ToggleNoKeySelected from '$lib/components/advancedkey/toggle/ToggleNoKeySelected.svelte';

  interface Props {
    onBack: () => void;
  }

  let { onBack }: Props = $props();

  let currentSelectedIndex = $derived($selectedKeys.length > 0 ? $selectedKeys[0] : null);
  let selectedToggleAction = $state('KC_CAPS');
  let toggleMode = $state('press');
  let toggleState = $state(false);
  let toggleDeletingKeys = $state(new Set<string>());
  let toggleNewlyAddedKeys = $state(new Set<string>());

  const configuredToggleKeys = $derived(
    Object.entries($globalConfigurations).filter(([_, config]) => config.type === 'toggle')
  );

  function getCurrentToggleConfiguration() {
    if (currentSelectedIndex === null) return null;
    const keyId = `${currentSelectedIndex}`;
    const config = $globalConfigurations[keyId];
    if (config && config.type === 'toggle') {
      return config;
    }
    return {
      type: 'toggle',
      toggleAction: selectedToggleAction,
      toggleMode: toggleMode,
      toggleState: toggleState,
    };
  }

  function updateToggleConfiguration(): void {
    if (currentSelectedIndex === null) return;
    const keyId = `${currentSelectedIndex}`;
    updateGlobalConfiguration(keyId, {
      type: 'toggle',
      toggleAction: selectedToggleAction,
      toggleMode: toggleMode,
      toggleState: toggleState,
    });
  }

  function deleteToggleKey(keyId: string): void {
    toggleDeletingKeys.add(keyId);
    toggleDeletingKeys = new Set(toggleDeletingKeys);

    setTimeout(() => {
      resetGlobalConfiguration(keyId);
      toggleDeletingKeys.delete(keyId);
      toggleDeletingKeys = new Set(toggleDeletingKeys);
    }, 500);
  }

  function resetAllToggleKeys(): void {
    const keysToDelete = [...configuredToggleKeys.map(([keyId]) => keyId)];

    keysToDelete.forEach(keyId => {
      toggleDeletingKeys.add(keyId);
    });
    toggleDeletingKeys = new Set(toggleDeletingKeys);

    setTimeout(() => {
      keysToDelete.forEach(keyId => {
        resetGlobalConfiguration(keyId);
      });
      toggleDeletingKeys.clear();
      toggleDeletingKeys = new Set(toggleDeletingKeys);
    }, 500);
  }

  function applyToggleConfiguration(): void {
    if (currentSelectedIndex === null) return;
    const keyId = `${currentSelectedIndex}`;

    const isNewKey =
      !$globalConfigurations[keyId] || $globalConfigurations[keyId].type !== 'toggle';

    updateToggleConfiguration();

    if (isNewKey) {
      toggleNewlyAddedKeys.add(keyId);
      toggleNewlyAddedKeys = new Set(toggleNewlyAddedKeys);
      setTimeout(() => {
        toggleNewlyAddedKeys.delete(keyId);
        toggleNewlyAddedKeys = new Set(toggleNewlyAddedKeys);
      }, 600);
    }
  }

  const currentKeyName = $derived.by(() => {
    if (currentSelectedIndex === null) return 'No key selected';
    const controller = keyboardAPI.state.controller;
    if (!controller) return 'Unknown';

    try {
      const layoutJson = controller.get_layout_json();
      const layout = JSON.parse(layoutJson);
      const keys = layout;

      if (keys && keys[currentSelectedIndex]) {
        const key = keys[currentSelectedIndex];
        if (key.labels && key.labels.length > 0) {
          const label = key.labels.find((l: string) => l && l.trim());
          if (label) return label;
        }
      }
    } catch (e) {
      console.error('Error getting key label:', e);
    }

    return `Key ${currentSelectedIndex}`;
  });

  $effect(() => {
    if (currentSelectedIndex !== null) {
      const keyId = `${currentSelectedIndex}`;
      const config = $globalConfigurations[keyId];
      if (config && config.type === 'toggle') {
        selectedToggleAction = config.toggleAction || 'KC_CAPS';
        toggleMode = config.toggleMode || 'press';
        toggleState = config.toggleState || false;
      } else {
        selectedToggleAction = 'KC_CAPS';
        toggleMode = 'press';
        toggleState = false;
      }
    }
  });
</script>

<ToggleHeader
  {onBack}
  onApply={applyToggleConfiguration}
  onResetAll={resetAllToggleKeys}
  canApply={currentSelectedIndex !== null}
/>

<div class="p-4 sm:p-6 -mx-8">
  {#if currentSelectedIndex !== null}
    <div class="max-w-7xl mx-auto">
      <ToggleSelectedKeyInfo {currentKeyName} {currentSelectedIndex} {toggleState} />

      <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <div class="xl:col-span-2 space-y-6">
          <ToggleActionSelector
            {selectedToggleAction}
            onActionSelect={(action) => (selectedToggleAction = action)}
          />

          <ToggleModeSelector
            {toggleMode}
            onModeSelect={(mode) => (toggleMode = mode)}
          />

          <ToggleStateControl
            {toggleState}
            onStateToggle={() => (toggleState = !toggleState)}
          />
        </div>

        <div class="xl:col-span-1 space-y-6">
          <TogglePreview {currentKeyName} {selectedToggleAction} {toggleMode} {toggleState} />
          <ToggleInfoPanel {selectedToggleAction} {toggleMode} />

          {#if configuredToggleKeys.length > 0}
            <ToggleConfiguredKeys
              configuredKeys={configuredToggleKeys}
              deletingKeys={toggleDeletingKeys}
              newlyAddedKeys={toggleNewlyAddedKeys}
              onDeleteKey={deleteToggleKey}
            />
          {/if}
        </div>
      </div>
    </div>
  {:else}
    <ToggleNoKeySelected />
  {/if}
</div>
