// src/lib/components/advancedkey/NullBindMode.svelte
<script lang="ts">
  import { language, t } from '$lib/stores/LanguageStore.svelte';
  import { selectedKeys } from '$lib/stores/SelectedKeysStore';
  import { keyboardAPI, keyboardConnectionState } from '$lib/api/keyboardAPI.svelte';
  import { selectedLayer } from '$lib/stores/SelectedLayerStore.svelte';
  import {
    globalConfigurations,
    updateGlobalConfiguration,
    resetGlobalConfiguration,
  } from '$lib/types/AdvancedKeyShared';
  import * as ekc from 'emi-keyboard-controller';
  import {
    advancedKeys,
    dynamicKeys,
    rgbBaseConfig,
    rgbConfigs,
  } from '$lib/stores/ControllerStore.svelte';
  import Layer from '../remap/Layer.svelte';
  import DynamicMode from './DynamicMode.svelte';

  import NullBindHeader from '$lib/components/advancedkey/nullbind/NullBindHeader.svelte';
  import NullBindKeySelection from '$lib/components/advancedkey/nullbind/NullBindKeySelection.svelte';
  import NullBindSelectedKeysInfo from '$lib/components/advancedkey/nullbind/NullBindSelectedKeysInfo.svelte';
  import NullBindBehaviorSelector from '$lib/components/advancedkey/nullbind/NullBindBehaviorSelector.svelte';
  import NullBindBottomOutControl from '$lib/components/advancedkey/nullbind/NullBindBottomOutControl.svelte';
  import NullBindBottomOutSlider from '$lib/components/advancedkey/nullbind/NullBindBottomOutSlider.svelte';
  import NullBindPerformanceTab from '$lib/components/advancedkey/nullbind/NullBindPerformanceTab.svelte';
  import NullBindKeyTesterTab from '$lib/components/advancedkey/nullbind/NullBindKeyTesterTab.svelte';
  import NullBindConfiguredKeys from '$lib/components/advancedkey/nullbind/NullBindConfiguredKeys.svelte';

  interface Props {
    onBack: () => void;
  }

  let { onBack }: Props = $props();

  let behavior = $state(0);
  let bottomOutPoint = $state(0);
  let actuationPoint = $state(1.5);
  let localSelectedKeys = $state<number[]>([]);
  let activeTab = $state<'performance' | 'key-tester'>('performance');
  let rtDown = $state(0);
  let rtUp = $state(0);
  let continuous = $state(false);
  let nullBindDeletingPairs = $state<Set<string>>(new Set());
  let nullBindNewlyAddedPairs = $state<Set<string>>(new Set());
  let uiBottomOutPoint = $state(4.0);
  let uiActuationPoint = $state(1.5);

  const SWITCH_DISTANCE = 4.0;
  const NULL_BIND_BEHAVIOR_METADATA = $derived([
    {
      behavior: 0,
      name: t('advancedkey.lastInputBehavior', $language),
      description: t('advancedkey.lastInputBehaviorDesc', $language),
    },
    {
      behavior: 1,
      name: t('advancedkey.absolutePriority1Behavior', $language),
      description: t('advancedkey.absolutePriority1BehaviorDesc', $language),
    },
    {
      behavior: 2,
      name: t('advancedkey.absolutePriority2Behavior', $language),
      description: t('advancedkey.absolutePriority2BehaviorDesc', $language),
    },
    {
      behavior: 3,
      name: t('advancedkey.neutralBehavior', $language),
      description: t('advancedkey.neutralBehaviorDesc', $language),
    },
    {
      behavior: 4,
      name: t('advancedkey.distanceBehavior', $language),
      description: t('advancedkey.distanceBehaviorDesc', $language),
    },
  ]);

  const configuredNullBindKeys = $derived(() => {
    const nullBindConfigs = Object.entries($globalConfigurations).filter(
      ([_, config]) => config.type === 'null-bind'
    );
    const uniquePairs = new Map();

    nullBindConfigs.forEach(([keyId, config]) => {
      const nullBindConfig = config as any;
      const pairKey = [...nullBindConfig.pairedKeys].sort().join('-');

      if (!uniquePairs.has(pairKey)) {
        uniquePairs.set(pairKey, [keyId, config]);
      }
    });

    return Array.from(uniquePairs.values());
  });

  const canConfigureNullBind = $derived(localSelectedKeys.length === 2);

  function updateNullBindConfiguration(): void {
    if (localSelectedKeys.length !== 2) return;

    const key1Label = getNullBindKeyLabel(localSelectedKeys[0]);
    const key2Label = getNullBindKeyLabel(localSelectedKeys[1]);

    localSelectedKeys.forEach(keyIndex => {
      const keyId = keyIndex.toString();
      const config: any = {
        type: 'null-bind',
        behavior: behavior,
        bottomOutPoint: bottomOutPoint,
        actuationPoint: actuationPoint,
        pairedKeys: [key1Label, key2Label],
        rtDown: rtDown,
        rtUp: rtUp,
        continuous: continuous,
      };

      updateGlobalConfiguration(keyId, config);
    });
  }

  function deleteNullBindPair(pairKeys: [string, string]): void {
    const pairId = `${pairKeys[0]}-${pairKeys[1]}`;

    nullBindDeletingPairs = new Set([...nullBindDeletingPairs, pairId]);

    setTimeout(() => {
      Object.entries($globalConfigurations).forEach(([keyId, config]) => {
        if (config.type === 'null-bind') {
          const nullConfig = config as any;
          if (
            (nullConfig.pairedKeys[0] === pairKeys[0] &&
              nullConfig.pairedKeys[1] === pairKeys[1]) ||
            (nullConfig.pairedKeys[0] === pairKeys[1] && nullConfig.pairedKeys[1] === pairKeys[0])
          ) {
            resetGlobalConfiguration(keyId);
          }
        }
      });

      nullBindDeletingPairs = new Set([...nullBindDeletingPairs].filter(id => id !== pairId));
    }, 300);
  }

  function applyNullBindConfiguration(): void {
    updateNullBindConfiguration();

    if (localSelectedKeys.length === 2) {
      const key1Label = getNullBindKeyLabel(localSelectedKeys[0]);
      const key2Label = getNullBindKeyLabel(localSelectedKeys[1]);

      const pairId1 = `${key1Label}-${key2Label}`;
      const pairId2 = `${key2Label}-${key1Label}`;
      const sortedPairId = [key1Label, key2Label].sort().join('-');

      nullBindNewlyAddedPairs = new Set([
        ...nullBindNewlyAddedPairs,
        pairId1,
        pairId2,
        sortedPairId,
      ]);

      setTimeout(() => {
        nullBindNewlyAddedPairs = new Set(
          [...nullBindNewlyAddedPairs].filter(
            id => id !== pairId1 && id !== pairId2 && id !== sortedPairId
          )
        );
      }, 500);
      let dynamic_key = new ekc.DynamicKeyMutex();
      dynamic_key.type = ekc.DynamicKeyType.DynamicKeyMutex;
      //dynamic_key.bindings[0] = ;
      //dynamic_key.bindings[1] = ;
      //dynamic_key.bindings[2] = ;
      //dynamic_key.bindings[3] = ;

      dynamic_key.target_keys_location[0] = new ekc.KeyLocation();
      dynamic_key.target_keys_location[1] = new ekc.KeyLocation();
      dynamic_key.target_keys_location[0].id = localSelectedKeys[0];
      dynamic_key.target_keys_location[0].layer = $selectedLayer;
      dynamic_key.target_keys_location[1].id = localSelectedKeys[1];
      dynamic_key.target_keys_location[1].layer = $selectedLayer;
      dynamic_key.key_id[0] = localSelectedKeys[0];
      dynamic_key.key_id[1] = localSelectedKeys[1];
      dynamic_key.mode = behavior;
    }

    // Clear selection
    localSelectedKeys = [];
  }

  function getNullBindKeyLabel(keyIndex: number): string {
    const controller = keyboardAPI.state.controller;
    if (!controller) return 'Unknown';

    try {
      const layoutJson = controller.get_layout_json();
      const layout = JSON.parse(layoutJson);
      const keys = layout;

      if (keys && keys[keyIndex]) {
        const key = keys[keyIndex];
        const label =
          key.labels?.[4] ||
          key.labels?.[0] ||
          key.labels?.find((l: string) => l && l.trim() !== '');
        return label || 'Unknown';
      }
    } catch (e) {
      console.error('Error getting key label:', e);
    }

    return 'Unknown';
  }

  function getNullBindBehaviorName(behaviorValue: number): string {
    const metadata = NULL_BIND_BEHAVIOR_METADATA.find(m => m.behavior === behaviorValue);
    return metadata ? metadata.name : 'Unknown';
  }

  function updateNullBindBottomOut(enabled: boolean): void {
    bottomOutPoint = enabled ? 4.0 : 0;
    if (enabled) {
      uiBottomOutPoint = 4.0;
    }
  }

  function updateNullBindRapidTrigger(enabled: boolean): void {
    if (enabled) {
      rtDown = 0.1;
      rtUp = 0;
      continuous = false;
    } else {
      rtDown = 0;
      rtUp = 0;
      continuous = false;
    }
  }

  function commitNullBindBottomOutPoint(): void {
    bottomOutPoint = uiBottomOutPoint;
  }

  function commitNullBindActuationPoint(): void {
    actuationPoint = uiActuationPoint;
  }

  $effect(() => {
    localSelectedKeys = $selectedKeys.slice(0, 2);
  });

  $effect(() => {
    if (bottomOutPoint > 0) {
      uiBottomOutPoint = bottomOutPoint;
    }
  });

  $effect(() => {
    uiActuationPoint = actuationPoint;
  });

  $effect(() => {
    if (localSelectedKeys.length === 2) {
      const firstKeyIndex = localSelectedKeys[0];
      const keyId = firstKeyIndex.toString();
      const existingConfig = $globalConfigurations[keyId] as any | undefined;

      if (existingConfig && existingConfig.type === 'null-bind') {
        behavior = existingConfig.behavior;
        bottomOutPoint = existingConfig.bottomOutPoint;
        actuationPoint = existingConfig.actuationPoint;
        uiActuationPoint = existingConfig.actuationPoint;
        if (existingConfig.bottomOutPoint > 0) {
          uiBottomOutPoint = existingConfig.bottomOutPoint;
        }
        rtDown = existingConfig.rtDown;
        rtUp = existingConfig.rtUp;
        continuous = existingConfig.continuous;
      }
    }
  });
</script>

<NullBindHeader {onBack} onApply={applyNullBindConfiguration} canApply={canConfigureNullBind} />

{#if !canConfigureNullBind}
  <NullBindKeySelection
    {localSelectedKeys}
    getKeyLabel={getNullBindKeyLabel}
    onRemoveKey={index => {
      const keyIndexToRemove = localSelectedKeys[index];
      if (keyIndexToRemove !== undefined) {
        localSelectedKeys = localSelectedKeys.filter((_, i) => i !== index);
      }
    }}
  />
{/if}

{#if canConfigureNullBind}
  <div class="flex-1 p-6">
    <div class="max-w-7xl mx-auto">
      <div class="flex w-full gap-8">
        <div class="flex w-72 flex-col gap-4">
          <NullBindSelectedKeysInfo {localSelectedKeys} getKeyLabel={getNullBindKeyLabel} />

          <NullBindBehaviorSelector
            {behavior}
            behaviorMetadata={NULL_BIND_BEHAVIOR_METADATA}
            onBehaviorSelect={b => (behavior = b)}
          />

          <NullBindBottomOutControl {bottomOutPoint} onBottomOutToggle={updateNullBindBottomOut} />

          <NullBindBottomOutSlider
            {bottomOutPoint}
            {actuationPoint}
            {uiBottomOutPoint}
            switchDistance={SWITCH_DISTANCE}
            onBottomOutPointChange={value => (uiBottomOutPoint = value)}
            onCommitBottomOutPoint={commitNullBindBottomOutPoint}
          />
        </div>

        <div class="flex flex-1 flex-col">
          <div class="border-gray-200 dark:border-white border-b">
            <nav class="-mb-px flex space-x-8">
              <button
                class="py-2 px-1 border-b-2 font-medium text-sm transition-colors hover:text-gray-700 dark:hover:text-gray-200 hover:border-gray-300 dark:hover:border-gray-600 {activeTab ===
                'performance'
                  ? 'border-primary-500 text-primary-500'
                  : 'border-transparent text-gray-500 dark:text-gray-400'}"
                onclick={() => (activeTab = 'performance')}
              >
                {t('advancedkey.performance', $language)}
              </button>
              <button
                class="py-2 px-1 border-b-2 font-medium text-sm transition-colors hover:text-gray-700 dark:hover:text-gray-200 hover:border-gray-300 dark:hover:border-gray-600 {activeTab ===
                'key-tester'
                  ? 'border-primary-500 text-primary-500'
                  : 'border-transparent text-gray-500 dark:text-gray-400'}"
                onclick={() => (activeTab = 'key-tester')}
              >
                {t('advancedkey.keyTester', $language)}
              </button>
            </nav>
          </div>

          <div class="flex-1 mt-6">
            {#if activeTab === 'performance'}
              <NullBindPerformanceTab />
            {:else if activeTab === 'key-tester'}
              <NullBindKeyTesterTab
                {localSelectedKeys}
                getKeyLabel={getNullBindKeyLabel}
                {behavior}
                {bottomOutPoint}
                {rtDown}
                getBehaviorName={getNullBindBehaviorName}
              />
            {/if}
          </div>
        </div>
      </div>
    </div>
  </div>
{/if}

{#if configuredNullBindKeys().length > 0}
  <NullBindConfiguredKeys
    configuredKeys={configuredNullBindKeys()}
    deletingPairs={nullBindDeletingPairs}
    newlyAddedPairs={nullBindNewlyAddedPairs}
    onDeletePair={deleteNullBindPair}
    getBehaviorName={getNullBindBehaviorName}
  />
{/if}

// src/features/dynamic-keys/components/NullBindMode.tsx
/**
 * Null-bind editor (port of `advancedkey/NullBindMode.svelte`): a mutex on the first two selected
 * keys of the selected layer. Apply sends the behavior's firmware mode plus the bottom-out flag
 * (D13) and each key's own binding; the other fields are UI-only (D5). The configured list and
 * its deletes are the keyboard's mutexes, one card per pair.
 */
import { useState } from 'react';
import {
  deviceSession,
  deviceStore,
  useDeviceConfig,
  type DeviceConfig,
  type KeyLocation,
} from '../../device';
import { useSelectedKeys, useSelectedLayer } from '../../keyboard';
import { useT } from '../../../lib/i18n';
import { removeDynamicKeyAt } from '../commands';
import { useLoadedDraft } from '../hooks/use-loaded-draft';
import { useTimeouts } from '../hooks/use-timeouts';
import {
  configuredMutexes,
  dynamicKeyOfKindAt,
  dynamicKeySignature,
  locationKey,
  ownBinding,
  type ConfiguredMutex,
} from '../model/configured-keys';
import {
  NULL_BIND_DRAFT,
  NULL_BIND_FIELD_DEFAULTS,
  NULL_BIND_SWITCH_DISTANCE_MM,
  loadNullBindDraft,
  mutexDraft,
  mutexFields,
  nullBindFieldsOnApply,
  withBottomOut,
  type NullBindDraft,
} from '../model/editor-drafts';
import { UNKNOWN_KEY_NAME } from '../model/key-names';
import { NULL_BIND_BEHAVIORS } from '../model/null-bind';
import { uiFields, useUiFields, type UiFieldsState } from '../store/ui-fields';
import { NullBindConfiguredKeys } from './nullbind/NullBindConfiguredKeys';
import {
  NullBindBehaviorSelector,
  NullBindBottomOutControl,
  NullBindBottomOutSlider,
  NullBindHeader,
  NullBindKeySelection,
  NullBindKeyTesterTab,
  NullBindSelectedKeysInfo,
  type KeyLabel,
} from './nullbind/NullBindParts';
import { NullBindPerformanceTab } from './nullbind/NullBindPerformanceTab';
import { NO_KEYS, withKey, withoutKey } from './shared/key-sets';

const DELETE_ANIMATION_MS = 300;
const ADDED_ANIMATION_MS = 500;

type Tab = 'performance' | 'key-tester';

/** The Svelte label lookup always fell back to "Unknown" (see `key-names.ts`). */
const getNullBindKeyLabel: KeyLabel = () => UNKNOWN_KEY_NAME;

/**
 * What the editor loads from: a pair whose first key runs a mutex loads it and the fields
 * remembered under the mutex's first key.
 */
function nullBindSource(
  config: DeviceConfig | null,
  nullBind: UiFieldsState['nullBind'],
  layer: number,
  pair: readonly number[]
) {
  const [first] = pair;
  const firstKey = pair.length === 2 && first !== undefined ? { layer, id: first } : null;
  const mutex = dynamicKeyOfKindAt(config, firstKey, 'mutex');
  const memoryKey = mutex?.dynamicKey.targets[0] ?? null;
  const fields = memoryKey ? nullBind[locationKey(memoryKey)] : undefined;
  return {
    mutex,
    fields,
    deps: [
      layer,
      pair.join(','),
      dynamicKeySignature(mutex?.dynamicKey ?? null),
      fields?.bottomOutMm,
    ],
  };
}

/** The editor's pair: the first two selected keys, until "Remove" drops one (Svelte local). */
interface LocalSelection {
  /** The selection this override was made for; a new selection resets it. */
  readonly source: readonly number[];
  readonly keys: readonly number[];
}

export interface NullBindModeProps {
  readonly onBack: () => void;
}

export function NullBindMode({ onBack }: NullBindModeProps) {
  const t = useT();
  const selectedKeys = useSelectedKeys();
  const layer = useSelectedLayer() - 1;
  const config = useDeviceConfig();
  const nullBindFields = useUiFields(state => state.nullBind);
  const schedule = useTimeouts();

  const [localSelection, setLocalSelection] = useState<LocalSelection | null>(null);
  const localSelectedKeys =
    localSelection?.source === selectedKeys ? localSelection.keys : selectedKeys.slice(0, 2);
  const canConfigureNullBind = localSelectedKeys.length === 2;

  const source = nullBindSource(config, nullBindFields, layer, localSelectedKeys);
  const { draft, update } = useLoadedDraft<NullBindDraft>(
    source.deps,
    previous => loadNullBindDraft(source.mutex?.dynamicKey ?? null, source.fields, previous),
    () => NULL_BIND_DRAFT
  );
  // A configured pair shows its remembered values, other pairs the editor defaults.
  const pairFields = source.mutex
    ? mutexFields(source.mutex.dynamicKey, source.fields)
    : NULL_BIND_FIELD_DEFAULTS;
  const [activeTab, setActiveTab] = useState<Tab>('performance');
  const [deletingPairs, setDeletingPairs] = useState(NO_KEYS);
  const [newlyAddedPairs, setNewlyAddedPairs] = useState(NO_KEYS);

  const configuredPairs = configuredMutexes(config?.dynamicKeys ?? []);

  function getNullBindBehaviorName(behaviorValue: number): string {
    const metadata = NULL_BIND_BEHAVIORS.find(option => option.behavior === behaviorValue);
    return metadata ? t(metadata.nameKey) : 'Unknown';
  }

  function deleteNullBindPair(pair: ConfiguredMutex): void {
    const pairId = locationKey(pair.targets[0]);
    setDeletingPairs(pairs => withKey(pairs, pairId));
    schedule(
      () => {
        removeDynamicKeyAt(pair.targets[0], 'mutex');
        setDeletingPairs(pairs => withoutKey(pairs, pairId));
      },
      DELETE_ANIMATION_MS,
      { flushOnUnmount: true }
    );
  }

  function applyNullBindConfiguration(): void {
    const [first, second] = localSelectedKeys;
    if (first !== undefined && second !== undefined && localSelectedKeys.length === 2) {
      const targets: readonly [KeyLocation, KeyLocation] = [
        { layer, id: first },
        { layer, id: second },
      ];
      const bindings = [ownBinding(config, targets[0]), ownBinding(config, targets[1])] as const;
      const remembered = source.mutex ? pairFields : undefined;
      // null: no free slot; the editor keeps its state (the device layer logs the rejection).
      if (deviceSession.applyDynamicKey(mutexDraft(targets, bindings, draft)) === null) return;

      const applied = dynamicKeyOfKindAt(deviceStore.getState().config, targets[0], 'mutex');
      const memoryKey = applied?.dynamicKey.targets[0] ?? targets[0];
      uiFields.setNullBind(memoryKey, nullBindFieldsOnApply(draft, remembered));
      const pairId = locationKey(memoryKey);
      setNewlyAddedPairs(pairs => withKey(pairs, pairId));
      schedule(() => {
        setNewlyAddedPairs(pairs => withoutKey(pairs, pairId));
      }, ADDED_ANIMATION_MS);
    }

    // Clear selection
    setLocalSelection({ source: selectedKeys, keys: [] });
  }

  const tabClass = (tab: Tab) =>
    `py-2 px-1 border-b-2 font-medium text-sm transition-colors hover:text-gray-700 dark:hover:text-gray-200 hover:border-gray-300 dark:hover:border-gray-600 ${
      activeTab === tab
        ? 'border-primary-500 text-primary-500'
        : 'border-transparent text-gray-500 dark:text-gray-400'
    }`;

  return (
    <>
      <NullBindHeader
        onBack={onBack}
        onApply={applyNullBindConfiguration}
        canApply={canConfigureNullBind}
      />

      {!canConfigureNullBind && (
        <NullBindKeySelection
          localSelectedKeys={localSelectedKeys}
          getKeyLabel={getNullBindKeyLabel}
          onRemoveKey={index => {
            if (localSelectedKeys[index] !== undefined) {
              setLocalSelection({
                source: selectedKeys,
                keys: localSelectedKeys.filter((_, i) => i !== index),
              });
            }
          }}
        />
      )}

      {canConfigureNullBind && (
        <div className="flex-1 p-6">
          <div className="max-w-7xl mx-auto">
            <div className="flex w-full gap-8">
              <div className="flex w-72 flex-col gap-4">
                <NullBindSelectedKeysInfo
                  localSelectedKeys={localSelectedKeys}
                  getKeyLabel={getNullBindKeyLabel}
                />

                <NullBindBehaviorSelector
                  behavior={draft.behavior}
                  onBehaviorSelect={behavior => {
                    update(current => ({ ...current, behavior }));
                  }}
                />

                <NullBindBottomOutControl
                  bottomOutPoint={draft.bottomOutMm}
                  onBottomOutToggle={enabled => {
                    update(current => withBottomOut(current, enabled));
                  }}
                />

                <NullBindBottomOutSlider
                  bottomOutPoint={draft.bottomOutMm}
                  actuationPoint={pairFields.actuationMm}
                  uiBottomOutPoint={draft.uiBottomOutMm}
                  switchDistance={NULL_BIND_SWITCH_DISTANCE_MM}
                  onBottomOutPointChange={uiBottomOutMm => {
                    update(current => ({ ...current, uiBottomOutMm }));
                  }}
                  onCommitBottomOutPoint={() => {
                    update(current => ({ ...current, bottomOutMm: current.uiBottomOutMm }));
                  }}
                />
              </div>

              <div className="flex flex-1 flex-col">
                <div className="border-gray-200 dark:border-white border-b">
                  <nav className="-mb-px flex space-x-8">
                    <button
                      type="button"
                      aria-pressed={activeTab === 'performance'}
                      className={tabClass('performance')}
                      onClick={() => {
                        setActiveTab('performance');
                      }}
                    >
                      {t('advancedkey.performance')}
                    </button>
                    <button
                      type="button"
                      aria-pressed={activeTab === 'key-tester'}
                      className={tabClass('key-tester')}
                      onClick={() => {
                        setActiveTab('key-tester');
                      }}
                    >
                      {t('advancedkey.keyTester')}
                    </button>
                  </nav>
                </div>

                <div className="flex-1 mt-6">
                  {activeTab === 'performance' ? (
                    <NullBindPerformanceTab selectedKeys={selectedKeys} layer={layer} />
                  ) : (
                    <NullBindKeyTesterTab
                      localSelectedKeys={localSelectedKeys}
                      getKeyLabel={getNullBindKeyLabel}
                      behavior={draft.behavior}
                      bottomOutPoint={draft.bottomOutMm}
                      rtDown={pairFields.rtDown}
                      getBehaviorName={getNullBindBehaviorName}
                    />
                  )}
                </div>
              </div>
            </div>
          </div>
        </div>
      )}

      {configuredPairs.length > 0 && (
        <NullBindConfiguredKeys
          configuredPairs={configuredPairs}
          deletingPairs={deletingPairs}
          newlyAddedPairs={newlyAddedPairs}
          onDeletePair={deleteNullBindPair}
          getKeyLabel={getNullBindKeyLabel}
          getBehaviorName={getNullBindBehaviorName}
        />
      )}
    </>
  );
}
