// src/lib/components/advancedkey/TapHoldMode.svelte
<script lang="ts">
  import { glassmorphismMode } from '$lib/stores/DarkModeStore.svelte';
  import { language, t } from '$lib/stores/LanguageStore.svelte';
  import { selectedKeys } from '$lib/stores/SelectedKeysStore';
  import { keyboardAPI } from '$lib/api/keyboardAPI.svelte';
  import {
    globalConfigurations,
    updateGlobalConfiguration,
    resetGlobalConfiguration,
  } from '$lib/types/AdvancedKeyShared';

  import TapHoldSelectedKeyInfo from '$lib/components/advancedkey/tap-hold/TapHoldSelectedKeyInfo.svelte';
  import TapHoldActionSelector from '$lib/components/advancedkey/tap-hold/TapHoldActionSelector.svelte';
  import TapHoldTimingConfig from '$lib/components/advancedkey/tap-hold/TapHoldTimingConfig.svelte';
  import TapHoldPreview from '$lib/components/advancedkey/tap-hold/TapHoldPreview.svelte';
  import TapHoldInfoPanel from '$lib/components/advancedkey/tap-hold/TapHoldInfoPanel.svelte';
  import TapHoldConfiguredKeys from '$lib/components/advancedkey/tap-hold/TapHoldConfiguredKeys.svelte';
  import TapHoldNoKeySelected from '$lib/components/advancedkey/tap-hold/TapHoldNoKeySelected.svelte';
  import TapHoldHeader from '$lib/components/advancedkey/tap-hold/TapHoldHeader.svelte';

  interface Props {
    onBack: () => void;
  }

  let { onBack }: Props = $props();

  let currentLanguage = $derived($language);

  type TapHoldConfiguration = {
    type: 'tap-hold';
    tapAction: string;
    holdAction: string;
    holdDelay: number;
    tapTimeout: number;
  };

  let currentSelectedIndex = $derived($selectedKeys.length > 0 ? $selectedKeys[0] : null);
  let tapAction = $state('KC_ESC');
  let holdAction = $state('KC_LCTL');
  let holdDelay = $state(200);
  let tapTimeout = $state(150);
  let deletingKeys = $state(new Set<string>());
  let newlyAddedKeys = $state(new Set<string>());

  const configuredTapHoldKeys = $derived(
    Object.entries($globalConfigurations).filter(([_, config]) => config.type === 'tap-hold')
  );

  function getCurrentKeyConfiguration(): TapHoldConfiguration | null {
    if (currentSelectedIndex === null) return null;
    const keyId = `${currentSelectedIndex}`;
    const config = $globalConfigurations[keyId];

    if (config && config.type === 'tap-hold') {
      return config as TapHoldConfiguration;
    }

    return {
      type: 'tap-hold',
      tapAction: tapAction,
      holdAction: holdAction,
      holdDelay: holdDelay,
      tapTimeout: tapTimeout,
    };
  }

  function updateConfiguration(): void {
    if (currentSelectedIndex === null) return;
    const keyId = `${currentSelectedIndex}`;
    const config: TapHoldConfiguration = {
      type: 'tap-hold',
      tapAction: tapAction,
      holdAction: holdAction,
      holdDelay: holdDelay,
      tapTimeout: tapTimeout,
    };
    updateGlobalConfiguration(keyId, config);
  }

  function deleteKey(keyId: string): void {
    deletingKeys.add(keyId);
    deletingKeys = new Set(deletingKeys);

    setTimeout(() => {
      resetGlobalConfiguration(keyId);
      deletingKeys.delete(keyId);
      deletingKeys = new Set(deletingKeys);
    }, 500);
  }

  function resetAllConfigurations(): void {
    const keysToDelete = [...configuredTapHoldKeys.map(([keyId]) => keyId)];

    keysToDelete.forEach(keyId => {
      deletingKeys.add(keyId);
    });
    deletingKeys = new Set(deletingKeys);

    setTimeout(() => {
      keysToDelete.forEach(keyId => {
        resetGlobalConfiguration(keyId);
      });
      deletingKeys.clear();
      deletingKeys = new Set(deletingKeys);
    }, 500);
  }

  function applyConfiguration(): void {
    if (currentSelectedIndex === null) return;
    const keyId = `${currentSelectedIndex}`;

    const isNewKey =
      !$globalConfigurations[keyId] || $globalConfigurations[keyId].type !== 'tap-hold';

    updateConfiguration();

    if (isNewKey) {
      newlyAddedKeys.add(keyId);
      newlyAddedKeys = new Set(newlyAddedKeys);
      setTimeout(() => {
        newlyAddedKeys.delete(keyId);
        newlyAddedKeys = new Set(newlyAddedKeys);
      }, 600);
    }
  }

  const currentKeyName = $derived.by(() => {
    if (currentSelectedIndex === null) return 'No key selected';
    const controller = keyboardAPI.state.controller;
    if (!controller) return 'Unknown';

    try {
      const layoutJson = controller.get_layout_json();
      const layout = JSON.parse(layoutJson);
      const keys = layout;

      if (keys && keys[currentSelectedIndex]) {
        const key = keys[currentSelectedIndex];
        if (key.labels && key.labels.length > 0) {
          const label = key.labels.find((l: string) => l && l.trim());
          if (label) return label;
        }
      }
    } catch (e) {
      console.error('Error getting key label:', e);
    }

    return `Key ${currentSelectedIndex}`;
  });

  $effect(() => {
    if (currentSelectedIndex !== null) {
      const config = getCurrentKeyConfiguration();
      if (config && $globalConfigurations[`${currentSelectedIndex}`]) {
        tapAction = config.tapAction || 'KC_ESC';
        holdAction = config.holdAction || 'KC_LCTL';
        holdDelay = config.holdDelay || 200;
        tapTimeout = config.tapTimeout || 150;
      }
    }
  });
</script>

<TapHoldHeader
  {currentSelectedIndex}
  {onBack}
  onApply={applyConfiguration}
  onResetAll={resetAllConfigurations}
/>

<div class="p-4 sm:p-6 -mx-8">
  {#if currentSelectedIndex !== null}
    <div class="max-w-7xl mx-auto">
      <TapHoldSelectedKeyInfo {currentKeyName} {currentSelectedIndex} />

      <div class="grid grid-cols-1 xl:grid-cols-3 gap-6">
        <div class="xl:col-span-2 space-y-6">
          <TapHoldActionSelector
            title="Tap Action"
            description="Select the action to perform when the key is tapped quickly"
            bind:selectedAction={tapAction}
            onActionSelect={action => (tapAction = action)}
            highlightColor="primary"
          />

          <TapHoldActionSelector
            title="Hold Action"
            description="Select the action to perform when the key is held down"
            bind:selectedAction={holdAction}
            onActionSelect={action => (holdAction = action)}
            highlightColor="green"
          />

          <TapHoldTimingConfig bind:holdDelay bind:tapTimeout />
        </div>

        <div class="xl:col-span-1 space-y-6">
          <TapHoldPreview {currentKeyName} {tapAction} {holdAction} {holdDelay} />
          <TapHoldInfoPanel {tapAction} {holdAction} {tapTimeout} {holdDelay} />
          <TapHoldConfiguredKeys {deletingKeys} {newlyAddedKeys} onDeleteKey={deleteKey} />
        </div>
      </div>
    </div>
  {:else}
    <TapHoldNoKeySelected />
  {/if}
</div>

// src/features/dynamic-keys/components/TapHoldMode.tsx
/**
 * Tap-hold editor (port of `advancedkey/TapHoldMode.svelte`): a mod-tap on the first selected key
 * of the selected layer. Apply writes it with `applyDynamicKey` (D6, D15); the hold delay is
 * UI-only (D5); the configured list and its deletes are the keyboard's mod-taps.
 */
import { useState } from 'react';
import { NoKeySelected } from '../../../components/ui';
import {
  deviceSession,
  deviceStore,
  useDeviceConfig,
  type DeviceConfig,
  type KeyLocation,
} from '../../device';
import { useSelectedKeys, useSelectedLayer } from '../../keyboard';
import { removeDynamicKeyAt, removeDynamicKeysOfKind } from '../commands';
import { useLoadedDraft } from '../hooks/use-loaded-draft';
import { useTimeouts } from '../hooks/use-timeouts';
import {
  configuredKeys,
  dynamicKeyOfKindAt,
  dynamicKeySignature,
  locationKey,
  type ConfiguredKey,
} from '../model/configured-keys';
import {
  TAP_HOLD_DRAFT,
  loadTapHoldDraft,
  modTapDraft,
  type TapHoldDraft,
} from '../model/editor-drafts';
import { keyIndexName } from '../model/key-names';
import { uiFields, uiFieldsStore, useUiFields, type UiFieldsState } from '../store/ui-fields';
import { NO_KEYS, withKey, withKeys, withoutKey } from './shared/key-sets';
import { KeycodePicker } from './shared/KeycodePicker';
import { TapHoldConfiguredKeys } from './tap-hold/TapHoldConfiguredKeys';
import {
  TapHoldHeader,
  TapHoldInfoPanel,
  TapHoldPreview,
  TapHoldSelectedKeyInfo,
  TapHoldTimingConfig,
} from './tap-hold/TapHoldParts';

const DELETE_ANIMATION_MS = 500;
const ADDED_ANIMATION_MS = 600;

/** What the editor loads from: the key, its mod-tap and its remembered hold delay. */
function tapHoldSource(
  config: DeviceConfig | null,
  tapHold: UiFieldsState['tapHold'],
  target: KeyLocation | null
) {
  const modTap = dynamicKeyOfKindAt(config, target, 'modTap');
  const fields = target ? tapHold[locationKey(target)] : undefined;
  return {
    modTap,
    fields,
    deps: [target && locationKey(target), dynamicKeySignature(modTap?.dynamicKey ?? null), fields],
  };
}

export interface TapHoldModeProps {
  readonly onBack: () => void;
}

export function TapHoldMode({ onBack }: TapHoldModeProps) {
  const selectedKeys = useSelectedKeys();
  const layer = useSelectedLayer();
  const config = useDeviceConfig();
  const tapHoldFields = useUiFields(state => state.tapHold);
  const schedule = useTimeouts();

  const currentSelectedIndex = selectedKeys[0] ?? null;
  const target: KeyLocation | null =
    currentSelectedIndex === null ? null : { layer: layer - 1, id: currentSelectedIndex };
  const source = tapHoldSource(config, tapHoldFields, target);
  const { draft, update, adopt } = useLoadedDraft<TapHoldDraft>(
    source.deps,
    previous => loadTapHoldDraft(source.modTap?.dynamicKey ?? null, source.fields, previous),
    () => TAP_HOLD_DRAFT
  );
  const [deletingKeys, setDeletingKeys] = useState(NO_KEYS);
  const [newlyAddedKeys, setNewlyAddedKeys] = useState(NO_KEYS);

  const configuredTapHoldKeys = configuredKeys(config?.dynamicKeys ?? [], 'modTap');
  const currentKeyName =
    currentSelectedIndex === null ? 'No key selected' : keyIndexName(currentSelectedIndex);

  function deleteKey(entry: ConfiguredKey<'modTap'>): void {
    const keyId = locationKey(entry.target);
    setDeletingKeys(keys => withKey(keys, keyId));
    schedule(
      () => {
        removeDynamicKeyAt(entry.target, 'modTap');
        setDeletingKeys(keys => withoutKey(keys, keyId));
      },
      DELETE_ANIMATION_MS,
      { flushOnUnmount: true }
    );
  }

  function resetAllConfigurations(): void {
    const keysToDelete = configuredTapHoldKeys.map(entry => locationKey(entry.target));
    setDeletingKeys(keys => withKeys(keys, keysToDelete));
    schedule(
      () => {
        removeDynamicKeysOfKind('modTap');
        setDeletingKeys(NO_KEYS);
      },
      DELETE_ANIMATION_MS,
      { flushOnUnmount: true }
    );
  }

  function applyConfiguration(): void {
    if (!target) return;
    const keyId = locationKey(target);
    const isNewKey = source.modTap === null;
    // null: no free slot; the editor keeps its values (the device layer logs the rejection).
    if (deviceSession.applyDynamicKey(modTapDraft(target, draft)) === null) return;
    uiFields.setTapHold(target, { holdDelayMs: draft.holdDelayMs });
    adopt(
      draft,
      tapHoldSource(deviceStore.getState().config, uiFieldsStore.getState().tapHold, target).deps
    );
    if (isNewKey) {
      setNewlyAddedKeys(keys => withKey(keys, keyId));
      schedule(() => {
        setNewlyAddedKeys(keys => withoutKey(keys, keyId));
      }, ADDED_ANIMATION_MS);
    }
  }

  return (
    <>
      <TapHoldHeader
        currentSelectedIndex={currentSelectedIndex}
        onBack={onBack}
        onApply={applyConfiguration}
        onResetAll={resetAllConfigurations}
      />

      <div className="p-4 sm:p-6 -mx-8">
        {currentSelectedIndex !== null ? (
          <div className="max-w-7xl mx-auto">
            <TapHoldSelectedKeyInfo
              currentKeyName={currentKeyName}
              currentSelectedIndex={currentSelectedIndex}
            />

            <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
              <div className="xl:col-span-2 space-y-6">
                <KeycodePicker
                  title="Tap Action"
                  description="Select the action to perform when the key is tapped quickly"
                  selectedAction={draft.tap}
                  onActionSelect={tap => {
                    update(current => ({ ...current, tap }));
                  }}
                  defaultExpandedSection="Basic"
                />

                <KeycodePicker
                  title="Hold Action"
                  description="Select the action to perform when the key is held down"
                  selectedAction={draft.hold}
                  onActionSelect={hold => {
                    update(current => ({ ...current, hold }));
                  }}
                  defaultExpandedSection="Basic"
                />

                <TapHoldTimingConfig
                  holdDelay={draft.holdDelayMs}
                  tapTimeout={draft.tapTimeoutMs}
                  onHoldDelayChange={holdDelayMs => {
                    update(current => ({ ...current, holdDelayMs }));
                  }}
                  onTapTimeoutChange={tapTimeoutMs => {
                    update(current => ({ ...current, tapTimeoutMs }));
                  }}
                />
              </div>

              <div className="xl:col-span-1 space-y-6">
                <TapHoldPreview
                  currentKeyName={currentKeyName}
                  tapAction={draft.tap}
                  holdAction={draft.hold}
                  holdDelay={draft.holdDelayMs}
                />
                <TapHoldInfoPanel
                  tapAction={draft.tap}
                  holdAction={draft.hold}
                  tapTimeout={draft.tapTimeoutMs}
                  holdDelay={draft.holdDelayMs}
                />
                <TapHoldConfiguredKeys
                  configuredKeys={configuredTapHoldKeys}
                  deletingKeys={deletingKeys}
                  newlyAddedKeys={newlyAddedKeys}
                  onDeleteKey={deleteKey}
                />
              </div>
            </div>
          </div>
        ) : (
          <NoKeySelected tipKey="advancedkey.tapHoldTip" />
        )}
      </div>
    </>
  );
}
