// src/features/remap/components/TabNavigation.tsx
import type { ReactNode } from 'react';

export interface TabOption<Name extends string> {
  readonly name: Name;
  readonly icon: ReactNode;
}

export interface TabNavigationProps<Name extends string> {
  readonly tabs: readonly TabOption<Name>[];
  readonly activeTab: Name;
  readonly onTabChange: (tabName: Name) => void;
}

/**
 * The Remap categories (port of `remap/TabNavigation.svelte`; the glassmorphism style is always
 * on, as in the Svelte app).
 */
export function TabNavigation<Name extends string>({
  tabs,
  activeTab,
  onTabChange,
}: TabNavigationProps<Name>) {
  return (
    <nav className="flex flex-col gap-2 w-full" aria-label="Categories">
      {tabs.map(tab => {
        const isActive = activeTab === tab.name;
        return (
          <button
            key={tab.name}
            type="button"
            className={`w-full h-14 text-base font-medium px-4 py-3 rounded-lg transition-all duration-200 flex items-center gap-3 glassmorphism-tab${isActive ? ' active' : ''}`}
            onClick={() => {
              onTabChange(tab.name);
            }}
            aria-pressed={isActive}
          >
            <div
              className="flex items-center justify-center flex-shrink-0"
              style={{ fill: 'currentColor' }}
            >
              {tab.icon}
            </div>
            <span className="text-left">{tab.name}</span>
          </button>
        );
      })}
    </nav>
  );
}

// src/lib/components/remap/TabNavigation.svelte
<script lang="ts">
  import { glassmorphismMode } from '$lib/stores/DarkModeStore.svelte';

  interface TabOption {
    name: string;
    icon: string;
  }

  interface Props {
    tabs: TabOption[];
    activeTab: string;
    onTabChange: (tabName: string) => void;
  }

  let { tabs, activeTab, onTabChange }: Props = $props();
</script>

<nav class="flex flex-col gap-2 w-full">
  {#each tabs as tab}
    {@const isActive = activeTab === tab.name}
    <button
      class="w-full h-14 text-base font-medium px-4 py-3 rounded-lg transition-all duration-200
             flex items-center gap-3
             {$glassmorphismMode ? 'glassmorphism-tab' : ''}
             {$glassmorphismMode && isActive ? 'active' : ''}
             {!$glassmorphismMode && isActive ? 'text-white shadow-sm border-l-4' : ''}
             {!$glassmorphismMode && !isActive
        ? 'text-gray-600 dark:text-gray-300 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-gray-800 border-l-4 border-transparent'
        : ''}"
      style={!$glassmorphismMode && isActive
        ? 'background-color: var(--theme-color-primary); border-left-color: var(--theme-color-primary);'
        : ''}
      onclick={() => onTabChange(tab.name)}
    >
      {#if tab.icon}
        <div class="flex items-center justify-center flex-shrink-0" style="fill: currentColor">
          {@html tab.icon}
        </div>
      {/if}
      <span class="text-left">{tab.name}</span>
    </button>
  {/each}
</nav>
