// src/lib/components/ui/Modal.svelte
<!--
  Shared modal overlay component.
  Replaces 3+ duplicate modal backdrop implementations.

  Usage:
    <Modal onClose={handleClose}>
      <h3>Title</h3>
      <p>Content here</p>
    </Modal>

    <Modal onClose={handleClose} maxWidth="lg">
      <p>Content here</p>
    </Modal>
-->
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { fade } from 'svelte/transition';

  type ModalMaxWidth = 'sm' | 'md' | 'lg' | 'xl';

  interface Props {
    onClose: () => void;
    maxWidth?: ModalMaxWidth;
    class?: string;
    children: Snippet;
  }

  let { onClose, maxWidth = 'md', class: className = '', children }: Props = $props();

  const maxWidthClasses: Record<ModalMaxWidth, string> = {
    sm: 'max-w-sm',
    md: 'max-w-md',
    lg: 'max-w-lg',
    xl: 'max-w-xl',
  };

  function handleKeydown(e: KeyboardEvent) {
    if (e.key === 'Escape') {
      onClose();
    }
  }
</script>

<svelte:window onkeydown={handleKeydown} />

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
  class="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4"
  transition:fade={{ duration: 150 }}
  onclick={onClose}
>
  <div
    class="border border-gray-700 rounded-xl shadow-2xl {maxWidthClasses[maxWidth]} w-full p-6 glassmorphism-card {className}"
    onclick={e => e.stopPropagation()}
    role="dialog"
    aria-modal="true"
    tabindex="-1"
  >
    {@render children()}
  </div>
</div>

// src/components/ui/Modal.tsx
import { useEffect, type ReactNode } from 'react';
import { Transition, fade } from '../../lib/transitions';

export type ModalMaxWidth = 'sm' | 'md' | 'lg' | 'xl';

export interface ModalProps {
  /**
   * Replaces the parent's `{#if}` around the Svelte modal: keep the modal rendered and toggle
   * `open`, so it fades in when opened and out when closed.
   */
  open: boolean;
  onClose: () => void;
  maxWidth?: ModalMaxWidth;
  className?: string;
  children: ReactNode;
  /** Id of the element that names the dialog (usually its title). */
  labelledBy?: string;
  /** Id of the element that describes the dialog. */
  describedBy?: string;
}

const maxWidthClasses: Record<ModalMaxWidth, string> = {
  sm: 'max-w-sm',
  md: 'max-w-md',
  lg: 'max-w-lg',
  xl: 'max-w-xl',
};

/**
 * Shared modal overlay (port of `ui/Modal.svelte`). Escape anywhere and backdrop clicks call
 * `onClose`; focus returns to the previously focused element when the modal closes.
 */
export function Modal({
  open,
  onClose,
  maxWidth = 'md',
  className = '',
  children,
  labelledBy,
  describedBy,
}: ModalProps) {
  useEffect(() => {
    if (!open) return;
    const handleKeydown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', handleKeydown);
    return () => {
      window.removeEventListener('keydown', handleKeydown);
    };
  }, [open, onClose]);

  useEffect(() => {
    if (!open) return;
    const previouslyFocused = document.activeElement;
    return () => {
      if (previouslyFocused instanceof HTMLElement && previouslyFocused.isConnected) {
        previouslyFocused.focus({ preventScroll: true });
      }
    };
  }, [open]);

  return (
    <Transition show={open} transition={[fade, { duration: 150 }]}>
      {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-static-element-interactions -- backdrop click is a mouse shortcut; Escape closes from the keyboard */}
      <div
        className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4"
        onClick={() => {
          onClose();
        }}
      >
        {/* eslint-disable-next-line jsx-a11y/click-events-have-key-events, jsx-a11y/no-noninteractive-element-interactions -- only stops clicks from reaching the backdrop */}
        <div
          className={`border border-gray-700 rounded-xl shadow-2xl ${maxWidthClasses[maxWidth]} w-full p-6 glassmorphism-card ${className}`}
          onClick={event => {
            event.stopPropagation();
          }}
          role="dialog"
          aria-modal="true"
          aria-labelledby={labelledBy}
          aria-describedby={describedBy}
          tabIndex={-1}
        >
          {children}
        </div>
      </div>
    </Transition>
  );
}
